### ISSUE TITLE
No matching symbol 'RelaySay' in GameVotes.as

### ISSUE THREAD

**Issue by danylopez123** [wootguy/RockTheVote#5]
I've followed all of the steps to install the plugin, however, i check my AngelScript log and i get this:

ERROR: mypathtosvencoop/svencoop_addon/scripts/plugins/gamevotes.as (162, 3) : No matching symbol 'RelaySay'
ERROR: mypathtosvencoop/svencoop_addon/scripts/plugins/gamevotes.as (210, 4) : No matching symbol 'RelaySay'
ERROR: mypathtosvencoop/svencoop_addon/scripts/plugins/gamevotes.as (214, 4) : No matching symbol 'RelaySay'
ERROR: Plugin script compilation failed

**Comment by wootguy** [comment]
Download GameVotes.as again. The RelaySay stuff was pushed by accident.

**Comment by danylopez123** [comment]
Seems that it fixed the problem, thanks!
